services:
  mail-service:
    build: .
    container_name: mail-service
    environment:
      MAIL_HOST: ${MAIL_HOST:-smtp.example.com}
      MAIL_PORT: ${MAIL_PORT:-465}
      MAIL_USERNAME: ${MAIL_USERNAME:-noreply@example.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-changeme}
      MAIL_API_KEY: ${MAIL_API_KEY:-changeme}
    networks:
      - proxy-net
      - mail-net
    restart: unless-stopped

networks:
  proxy-net:
    name: proxy-net
    external: true
  mail-net:
    name: mail-net
